export const CMD_Reset = "\x1b[0m"
export const CMD_Bright = "\x1b[1m"
export const CMD_Dim = "\x1b[2m"
export const CMD_Underscore = "\x1b[4m"
export const CMD_Blink = "\x1b[5m"
export const CMD_Reverse = "\x1b[7m"
export const CMD_Hidden = "\x1b[8m"

export const CMD_FgBlack = "\x1b[30m"
export const CMD_FgRed = "\x1b[31m"
export const CMD_FgGreen = "\x1b[32m"
export const CMD_FgYellow = "\x1b[33m"
export const CMD_FgBlue = "\x1b[34m"
export const CMD_FgMagenta = "\x1b[35m"
export const CMD_FgCyan = "\x1b[36m"
export const CMD_FgWhite = "\x1b[37m"

export const CMD_BgBlack = "\x1b[40m"
export const CMD_BgRed = "\x1b[41m"
export const CMD_BgGreen = "\x1b[42m"
export const CMD_BgYellow = "\x1b[43m"
export const CMD_BgBlue = "\x1b[44m"
export const CMD_BgMagenta = "\x1b[45m"
export const CMD_BgCyan = "\x1b[46m"
export const CMD_BgWhite = "\x1b[47m"